-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 29, 2021 at 12:37 AM
-- Server version: 10.4.20-MariaDB
-- PHP Version: 7.3.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `os-system`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(10) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `description`, `created_at`, `updated_at`) VALUES
(2, 'Magnam tenetur esse tempore magnam consequuntur minus blanditiis.', 'Impedit quia nam dolor alias exercitationem iusto quod. Porro cupiditate adipisci repellat officiis dolorum. Eos temporibus beatae eveniet velit similique ab. Tempora rerum repellendus et iste placeat repudiandae.', '2021-10-28 19:05:51', '2021-10-28 19:05:51'),
(3, 'Enim est placeat voluptas.', 'Fugit veritatis eius assumenda. Est ea voluptas voluptatibus non. Amet et omnis sunt possimus aut autem molestiae. Sapiente laboriosam delectus eos amet totam iste. Et nihil deserunt necessitatibus natus facilis. Aliquid est nam quia id. Architecto est suscipit labore quia delectus cupiditate neque adipisci.', '2021-10-28 19:05:51', '2021-10-28 19:05:51'),
(4, 'Nam nam facilis alias et reprehenderit.', 'Aliquid nam impedit corrupti reprehenderit natus. Dolorem blanditiis ratione fugiat veritatis. Vitae perferendis dignissimos quia. Eos voluptatem reiciendis sint eos molestiae. Numquam laborum alias eius autem deleniti aperiam similique. Qui quis est et est eos aut ea. Sit qui occaecati dolor est ut nihil dolorem.', '2021-10-28 19:05:51', '2021-10-28 19:05:51'),
(5, 'Cumque at quia quis nihil reiciendis.', 'Debitis dignissimos quia voluptatem quibusdam. Voluptatum et deleniti qui vel. Facilis quia autem quidem eligendi voluptates ut. Quibusdam occaecati voluptatem et quaerat ad modi nihil. Omnis odio nostrum et facilis sint facere commodi et. Eum error molestias sit tenetur aut minima saepe iste.', '2021-10-28 19:05:51', '2021-10-28 19:05:51'),
(6, 'Soluta culpa iusto dicta aperiam natus provident dolores corrupti.', 'Quis velit sapiente rerum a mollitia est vero. Quia neque sint rerum laudantium. Delectus dolores iste rerum reiciendis eligendi. Alias sed ipsa amet non voluptatibus quo dolor.', '2021-10-28 19:05:51', '2021-10-28 19:05:51'),
(7, 'Libero molestiae et ea facere.', 'Asperiores et quisquam amet aliquid ut. Quia adipisci est explicabo ut nostrum. Voluptas et ea asperiores dicta alias voluptatibus. Blanditiis qui qui nisi. Maxime molestias mollitia aut magni voluptas.', '2021-10-28 19:05:52', '2021-10-28 19:05:52'),
(8, 'Ea sunt adipisci reprehenderit illo.', 'Quae dolore et quidem ipsa veritatis. Nihil nobis consequatur autem atque quas repudiandae quia. Est omnis sed aut excepturi et maxime. Ipsa dolorem sed et est quis dolor et. Eum nostrum aperiam facilis porro et earum reprehenderit. Provident a quae aperiam quia.', '2021-10-28 19:05:52', '2021-10-28 19:05:52'),
(9, 'Maxime magni placeat sit natus veritatis quibusdam repellat.', 'Dolor fuga laudantium quia voluptas eligendi facilis. Pariatur aspernatur totam quis architecto. Sed totam voluptas sint consectetur voluptatem. Aut debitis itaque nostrum veritatis qui sed nobis. Doloremque dolores expedita vel vel eaque ea.', '2021-10-28 19:05:52', '2021-10-28 19:05:52'),
(10, 'Velit adipisci possimus iure veritatis vero dolorem voluptas debitis.', 'Ut odio aut delectus quia qui omnis. Voluptatem dicta aperiam reprehenderit aut. Provident molestiae et est eius aperiam pariatur. Consequuntur ab ut cupiditate sit magnam. Aperiam assumenda dolorem corrupti ut laborum. Voluptas ut maxime inventore tempore similique.', '2021-10-28 19:05:52', '2021-10-28 19:05:52'),
(11, 'cnehj', 'xxxxxxxxxxx', '2021-10-28 20:57:43', '2021-10-28 20:57:43');

-- --------------------------------------------------------

--
-- Table structure for table `failed_jobs`
--

CREATE TABLE `failed_jobs` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `connection` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `queue` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `exception` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(11, '2014_10_12_000000_create_users_table', 1),
(12, '2014_10_12_100000_create_password_resets_table', 1),
(13, '2016_06_01_000001_create_oauth_auth_codes_table', 1),
(14, '2016_06_01_000002_create_oauth_access_tokens_table', 1),
(15, '2016_06_01_000003_create_oauth_refresh_tokens_table', 1),
(16, '2016_06_01_000004_create_oauth_clients_table', 1),
(17, '2016_06_01_000005_create_oauth_personal_access_clients_table', 1),
(18, '2019_08_19_000000_create_failed_jobs_table', 1),
(19, '2021_09_22_120740_create_posts_table', 1),
(20, '2021_09_22_121300_create_categories_table', 1);

-- --------------------------------------------------------

--
-- Table structure for table `oauth_access_tokens`
--

CREATE TABLE `oauth_access_tokens` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `client_id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `scopes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revoked` tinyint(1) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_auth_codes`
--

CREATE TABLE `oauth_auth_codes` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `client_id` bigint(20) UNSIGNED NOT NULL,
  `scopes` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `revoked` tinyint(1) NOT NULL,
  `expires_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_clients`
--

CREATE TABLE `oauth_clients` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `user_id` bigint(20) UNSIGNED DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `secret` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `provider` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `redirect` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `personal_access_client` tinyint(1) NOT NULL,
  `password_client` tinyint(1) NOT NULL,
  `revoked` tinyint(1) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_personal_access_clients`
--

CREATE TABLE `oauth_personal_access_clients` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `client_id` bigint(20) UNSIGNED NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `oauth_refresh_tokens`
--

CREATE TABLE `oauth_refresh_tokens` (
  `id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `access_token_id` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `revoked` tinyint(1) NOT NULL,
  `expires_at` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `password_resets`
--

CREATE TABLE `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `posts`
--

CREATE TABLE `posts` (
  `id` int(10) UNSIGNED NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `admin_id` int(11) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `category_id` int(10) UNSIGNED NOT NULL,
  `poster` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `posts`
--

INSERT INTO `posts` (`id`, `title`, `admin_id`, `description`, `category_id`, `poster`, `created_at`, `updated_at`) VALUES
(2, 'Rerum velit modi adipisci accusantium animi dolor.', 4, 'Autem impedit nesciunt aut voluptatum ut tenetur quae. Qui a quos exercitationem ducimus consequatur beatae. Qui ea sunt amet sit aliquam ratione eos. Aliquam modi aut itaque officia. Deleniti atque tempora ut corporis. Sit et consectetur dolores distinctio. Sapiente molestias consequatur sint qui eaque commodi debitis. Enim iste porro eveniet quibusdam ullam magnam. Delectus error nulla et tempora excepturi et. Consequatur reiciendis dolorem ex inventore a. Deserunt aut vel provident id et facilis amet. Sed iste in incidunt architecto alias. Architecto impedit occaecati et consequatur. Laudantium sunt sit eum aliquam quae quasi. Nobis aperiam et sit et. Ut molestiae distinctio officia praesentium et sunt. Blanditiis sit iste soluta consectetur inventore rerum vel. Voluptatem dolor ab quos laborum qui. Beatae dolor molestiae sed ea aliquid. Repellat cum temporibus et rerum incidunt voluptatum. Est sint temporibus voluptas eaque cupiditate aut. Aut in facilis ut qui fuga commodi est. Officia voluptate nulla quo incidunt assumenda. Ut ipsam ut deleniti eius harum qui. Repellat tempore animi est repellendus vel ex. Repellendus possimus sunt sit modi pariatur. Voluptatem id animi ut odit quia molestias. Velit qui praesentium qui nesciunt. Recusandae incidunt magni odit et. Eveniet vel est suscipit labore veritatis. Animi id ipsum repudiandae et sed sed. Et mollitia et rerum repellat et a. Natus nulla ipsa fugiat velit corporis. Quibusdam occaecati praesentium dolorem velit et ut quam. Minus labore tempore ad error. Eum omnis eum veniam. Delectus corporis doloribus temporibus quod. Et voluptates quisquam debitis doloremque. Quia velit numquam maiores labore pariatur quia.', 2, 'poster.png', '2021-10-28 19:05:47', '2021-10-28 19:05:47'),
(3, 'Quaerat consequatur et deserunt.', 1, 'Est sunt exercitationem repellendus. Optio excepturi est impedit iusto maiores sint. Ut quia animi ducimus excepturi. Facere nihil qui non dolorem maiores. Voluptates quas est quia ullam molestiae praesentium. Aut illum optio tempore nostrum sed. Eum eum id quis temporibus dolore. Ea qui earum omnis aut molestias. Recusandae dolores voluptatum quaerat velit cupiditate a. Earum tenetur quo et error. Possimus recusandae ea at et. Praesentium ex excepturi tempora eius. Quia quae quaerat distinctio in. Rem magnam placeat reprehenderit molestiae cupiditate. Autem autem aliquid qui nulla blanditiis cum. Id minus optio voluptatibus eos qui excepturi quis assumenda. Cum ad pariatur molestiae et ut. Reiciendis cumque qui voluptas nobis sit. Laudantium qui itaque id ut esse aut. Ut necessitatibus est ut aut similique corporis et. Natus maiores eum temporibus enim eos. Ea dignissimos ipsam veritatis doloremque qui aut fugiat totam. Maiores nam at ipsum.', 7, '617b210c2c5f8.png', '2021-10-28 19:05:47', '2021-10-28 21:15:40'),
(4, 'Quia doloribus sapiente delectus in laboriosam nihil autem tenetur.', 8, 'Pariatur laboriosam vero sunt modi sunt. Nostrum saepe et et qui commodi exercitationem consequatur. Ea perspiciatis at quod quas facilis aliquam accusamus. Cum est inventore aperiam. Ea eveniet possimus in quidem praesentium consequatur fugit. Perspiciatis ut adipisci eius. Ut autem vel repellendus culpa rerum cum. Ducimus eum officia placeat excepturi quod deserunt. Dolores ratione dolorum necessitatibus harum quidem quasi. Voluptates qui et molestiae debitis quas magnam excepturi. Voluptatem molestiae ut vel in voluptatem illum autem. Est nemo reiciendis itaque rem enim voluptatum. Hic iusto repudiandae dolore ullam. Nihil facilis ut voluptatem et suscipit reprehenderit dolorum. Et eligendi quos nulla voluptatem. Est inventore adipisci sint quos. Porro eligendi molestiae illum ab. Rerum voluptatem dolores nesciunt et optio. Excepturi veritatis delectus aut fugiat explicabo officia. Voluptatum aut exercitationem repellat quos incidunt totam molestiae. Excepturi rerum dolorum deleniti sint. Sunt nesciunt ea amet vero dolorem aut. Et commodi a sit ut aut et. Qui nobis officiis numquam nisi.', 7, 'poster.png', '2021-10-28 19:05:47', '2021-10-28 19:05:47'),
(5, 'Voluptate dolor vitae officiis culpa.', 5, 'Vero odit placeat et ut hic voluptates similique voluptatem. Occaecati voluptatem veniam sit voluptatibus iure. In dolores temporibus dolor dignissimos saepe. Dolores ullam quibusdam exercitationem laudantium eveniet. Neque sit illo dolorum quae et voluptatum. Facere hic commodi dolorem maxime. Atque et eum nisi exercitationem omnis quas. Doloribus autem quas iusto sed sed laborum. Numquam doloribus aperiam ratione incidunt aut aut. Eum porro amet sed ullam et modi rem et. Vitae vel omnis magni neque at. Reprehenderit quia vitae necessitatibus ex ut deserunt tempore. Dolorum sit voluptatibus magnam quae quo autem doloribus. Natus rem modi aliquid ut nam. Minima impedit id odio harum est doloremque. Corporis libero quo at voluptatum. Ullam et ipsa eum molestias sunt quam quasi. Et quia quo deserunt. Et assumenda quia rem sit incidunt illum. Et qui ad repellendus molestiae et. Qui deleniti voluptatem eos qui distinctio molestiae quo.', 8, 'poster.png', '2021-10-28 19:05:47', '2021-10-28 19:05:47'),
(6, 'Qui magnam ratione fugit illum.', 10, 'Repudiandae laudantium dicta quas. Blanditiis hic in magnam omnis cum voluptatum soluta. Sunt impedit enim quae omnis dignissimos. Modi nihil aperiam est quaerat fugit. Reiciendis asperiores at quam quia recusandae repellendus. Velit a beatae distinctio inventore iure. Ad et autem magni magni quod est laborum. Dolores error necessitatibus possimus delectus esse fugiat. Qui eaque in placeat autem enim rem. Ut ut consectetur enim autem. Placeat inventore sit commodi iure. Unde repellat expedita pariatur ratione nihil. Non culpa sed dolorum quae quas. Deserunt ipsam ea esse est et aspernatur. Vitae ipsam magni accusamus esse. Deserunt suscipit quasi et est quae sed modi. Eum occaecati doloribus aut dolorem cupiditate minima pariatur deserunt. Et aliquam sit temporibus necessitatibus. Blanditiis sequi iure tempora qui. Aut amet voluptatem ullam quasi.', 4, 'poster.png', '2021-10-28 19:05:47', '2021-10-28 19:05:47'),
(7, 'Aut deleniti ut consequuntur esse.', 3, 'Aut sit incidunt non eveniet. Architecto omnis voluptatem aliquam corrupti impedit quam est voluptas. Repellendus sint amet provident. Dolor atque id qui at eaque enim iure. Nihil cum quibusdam quod consequatur tempora qui nesciunt. Quam et excepturi occaecati dolore quos. Sint velit qui eius id. Dolorem quisquam et labore consectetur non ea aliquid. Hic culpa qui optio consequatur ratione autem aliquid. Et velit voluptatem deleniti unde in ut et. Sapiente quo quaerat accusamus tempora tempore deserunt. Voluptas omnis non deleniti sed. Ipsum asperiores modi voluptas cupiditate accusamus at repellat natus. Minima et sed velit non. Quia voluptatum consequatur rerum adipisci. Ipsa recusandae laudantium consequuntur architecto dolorem ratione porro. Et sit ad laborum voluptatum. Sed ut alias officiis nemo. Voluptas officia qui dolor ut tempora. Blanditiis dicta voluptatum culpa ea nemo esse ea. Aspernatur numquam deserunt inventore consequatur consequatur ut. Voluptatum rerum labore est numquam. Corporis blanditiis autem quae sed quia. Qui aut et molestiae similique. Perspiciatis quae laudantium consectetur rerum veniam omnis quasi. Aspernatur non sequi dolorem. Culpa quis ipsum amet laborum aut. Facere saepe quo similique ut incidunt repellendus. Ullam et deserunt rerum ut magni voluptatibus consequuntur. Facilis odio qui ex provident esse dolores omnis. Voluptate beatae dolor pariatur alias dolorem reiciendis. Debitis quidem saepe ut quia quam dignissimos voluptatem. Qui voluptas nulla ullam at doloribus ipsam voluptate. Quis nostrum in et quae voluptatem vel veritatis. Eaque voluptatem voluptatem architecto est et assumenda beatae. Voluptatem expedita veniam tenetur in mollitia. Consequatur nulla consequatur in eius quos sint architecto. Dolor ab aut qui quia a voluptas quo. Voluptas non quo tenetur distinctio dolor autem ut. Minima ex itaque veniam qui et harum.', 4, 'poster.png', '2021-10-28 19:05:47', '2021-10-28 19:05:47'),
(8, 'Corrupti ea et vitae nostrum harum.', 7, 'Velit ut doloremque in autem. Quibusdam molestiae ut reiciendis cum eos incidunt saepe aliquid. Nostrum est odit temporibus voluptates sunt sed aliquid distinctio. Sequi dignissimos deleniti vel odit. Perferendis error ut nisi ea qui rerum. Expedita impedit doloribus inventore similique et quod. Ut provident architecto ut a nihil et omnis. Autem qui voluptas sequi provident sunt. Laborum ullam ut consequatur omnis. Veritatis sed tempore qui distinctio omnis soluta et. Suscipit in minima blanditiis soluta et dolores. Quis magni ut omnis dolorum rerum qui alias. Id est placeat qui qui inventore velit. Qui voluptatem vel est illo eaque. Quos aut quo ut omnis esse unde. Facere dolorem enim pariatur facere exercitationem dignissimos voluptatem. Hic cupiditate qui ut aut eius aut numquam doloremque. Sed illum quidem amet sed dolorem. Quibusdam possimus est et et qui est quo nam. Cumque cum quas et similique quod quas et. Cum maiores voluptatem quibusdam ut earum beatae rerum. Est officiis ab voluptate cumque ut odit. Qui cum numquam et illum qui dolorem aperiam. Laudantium rerum et voluptate est sapiente. Quae quo corporis ducimus adipisci fugit sit. Aut tempore deleniti aut praesentium nesciunt est et. Ut aliquid dicta blanditiis numquam placeat enim. Vitae nobis quia non animi voluptatibus modi. Quia veritatis qui qui omnis ex ut qui possimus. Officia temporibus consequatur architecto est. Est non aperiam eos.', 3, 'poster.png', '2021-10-28 19:05:47', '2021-10-28 19:05:47'),
(9, 'Voluptatum maxime corporis non unde sint et optio id.', 8, 'Qui quia tempore cum officia quia explicabo nam aliquid. Natus aliquid ea velit ut eum beatae. Est cupiditate natus sint nihil. Ad molestiae quisquam exercitationem harum dignissimos. Tempore praesentium ut odio dolores qui. Cum nostrum illo eum reiciendis eius quos. Velit aut dolore accusantium. Et at sint provident delectus rerum. Laboriosam voluptatem vel aperiam rerum. Soluta nisi ea enim pariatur omnis odit laborum qui. Id nemo repudiandae repellat doloremque vero provident architecto ea. Illo et et et harum inventore. Consequuntur officia eos culpa ullam voluptatem. Error et incidunt impedit inventore. Blanditiis odio occaecati cum. Sint ad labore adipisci culpa qui. Quia incidunt autem magni. Nihil eveniet quae est doloremque enim perspiciatis. Rem eveniet expedita nobis qui quas. Incidunt ut et sed adipisci voluptatem. Mollitia quod ut beatae voluptates omnis voluptatibus in. Inventore molestias animi ipsam qui modi enim. Incidunt reprehenderit maiores harum laboriosam consequuntur tempora. Natus occaecati quas et est. Numquam ipsa aspernatur doloribus est. Est ratione maxime qui vitae incidunt et consequatur. Quia quod omnis quibusdam. Totam ut eos hic ut.', 5, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(10, 'Sint nostrum assumenda quis nostrum expedita necessitatibus qui et.', 1, 'Ipsa iste ut voluptatem ut eius modi culpa. Quam magnam sed ad molestias voluptatem. Aliquam architecto minus perferendis cumque pariatur beatae inventore et. Dolor numquam ut dolores ipsam voluptatem. Sit magnam iure quam rerum et. Corrupti velit eos nostrum dolores dolore et. Sit autem in natus quia aperiam. Inventore rerum dolor est nihil odit. Corrupti blanditiis et tempora odio. Dicta ullam aut est esse amet officia velit laudantium. Adipisci autem molestiae et totam. Voluptas natus est deleniti laborum animi eum alias. Omnis animi nesciunt nihil voluptas neque quidem temporibus. Ex cupiditate id vel rerum quis quae. Provident illum et repudiandae nemo et. Sed praesentium et velit. Corrupti excepturi libero et qui totam nulla. Qui cupiditate dolore facere est voluptates. Expedita perspiciatis sint consequatur corrupti eos. Dolor doloremque consequatur quia sapiente. Dicta quibusdam minima ut illo quis culpa. Molestias quis eum sint est sunt sit asperiores. Dolores est totam vitae labore voluptatem est sint aut. Sint sed dicta et non quaerat quos. Consequuntur qui non dolores aperiam voluptas dolores. Aut ut nostrum iure ut. Veniam et iure sed eos. Quia enim rem vitae. Saepe fuga et magnam nihil tempore inventore natus. Repellat exercitationem accusantium sequi eveniet. Vero cumque at pariatur quos ratione ut quis. Molestias libero laborum occaecati qui. Consectetur repellendus rerum odit molestias excepturi. Aut sit excepturi voluptates sunt ut ab. Totam alias delectus laboriosam. Ipsa voluptas libero rerum optio.', 3, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(12, 'Id cum beatae ipsa nesciunt.', 7, 'Ducimus minus numquam veritatis ab aut sint. Atque excepturi dolor optio sit ex sed nam ullam. Perspiciatis commodi sit sint et eum tenetur qui dolore. Dolor quia facilis perferendis vel delectus. Consequatur est qui hic nisi dicta ea nihil sint. Veritatis nemo et ut earum. Quia modi laboriosam est rem voluptatem maxime. Et veniam unde tempore libero quasi dignissimos magni. Possimus dolorum voluptatem perferendis et quia. Ipsa ipsa dolore commodi animi. Nihil et aut quo ipsa. Cum temporibus dignissimos voluptas consequatur ratione et consequuntur. Quis aspernatur quia quos rerum dolor. Eaque earum impedit perferendis qui occaecati. Et quis numquam labore. Quaerat veritatis dolorem molestias. Facilis atque eos et excepturi natus. Tempora voluptatibus eos et minima eius eum dolorem. Id velit minima amet quos blanditiis ut. Earum dolores quo magni nemo maxime. Id voluptate est alias. Autem qui quas qui impedit. Nam suscipit quam aperiam sit dolorem doloremque. Atque modi aut minima deleniti. Nostrum omnis sunt unde quos dolorem expedita. Sapiente sit molestias commodi non debitis. Unde soluta non et qui rem omnis earum. Et natus animi amet sed temporibus. Tenetur reprehenderit pariatur enim similique et. Quos aut et impedit adipisci. Qui accusamus ipsa cumque error.', 8, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(13, 'Quibusdam hic non corporis est.', 7, 'Facere neque amet non ad et quidem. Numquam consectetur voluptatibus quasi dolore. Molestiae nisi soluta officia adipisci ad quibusdam et. Beatae quam ratione atque aut accusamus aliquid molestiae. Quo non dolores est doloribus eum velit animi. Ipsam sit quos odit doloribus vitae. Est eos asperiores quos aspernatur. Corporis sed minus aut. In sunt perferendis cupiditate fugit. Quos molestiae repellat esse eligendi error consequatur. Asperiores possimus temporibus doloribus ut rerum magni qui. Et eos consequatur quam ratione. Molestiae maxime quam omnis earum. Vel corrupti fugiat recusandae in. Eos quam velit fugit delectus facere quo non quaerat. Reprehenderit reprehenderit aut sapiente hic itaque. Et alias deleniti nihil ratione. Non non enim iste facere eos perferendis. Officia iusto esse aliquid ut nesciunt quisquam placeat. Quia iste odio et placeat officia. Dolor recusandae qui minus aliquid consequatur harum quae. Ad quisquam dolores voluptate nihil. Alias inventore recusandae quae tenetur nemo odio eum. Consequatur ex inventore minus quaerat. Voluptas velit at maxime sed expedita quos. Itaque quas laborum quasi et ut doloremque. Mollitia quas voluptate officiis accusantium ut ipsum. Enim eius neque laborum temporibus fuga. Ex illum autem voluptatem at et corporis ex error. Eveniet repellendus repudiandae ut quibusdam. Soluta quia et autem est id natus. Sit perferendis minus quos. Eum cumque doloribus voluptatum aut. Omnis explicabo culpa facere asperiores enim. Harum odio dolorum voluptatum magni et et dolore eos.', 2, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(14, 'Molestiae deserunt porro totam impedit est incidunt enim.', 1, 'Illo et maxime sed. Repudiandae laudantium molestiae dolor totam commodi. Quae culpa rerum et. Porro iste voluptatem aspernatur magni quia laboriosam nihil. Illum sed voluptatem molestiae ut vel quo doloremque. Nulla sed consectetur facere id. Est vitae eaque officia ut. Non cum molestiae in perspiciatis ex officia laborum perferendis. Impedit enim voluptas temporibus saepe. Dolor suscipit rerum sint itaque et deserunt. Qui consequatur itaque nesciunt beatae aut quis excepturi. Est voluptatibus quibusdam mollitia rerum reprehenderit dicta. Tenetur amet aut voluptatum perferendis. Quia iste facere cupiditate eveniet eveniet cumque omnis. Maxime soluta maiores dolores minus doloremque. Aperiam reprehenderit qui architecto impedit aut quo dicta. Quaerat et repudiandae non dolor optio sed tenetur. Qui nostrum mollitia delectus. Ut non qui ratione. Et ut optio est ut aut numquam repudiandae. Est similique autem at deleniti. Voluptatem et incidunt fugit consequatur facilis et maxime. Et suscipit repudiandae est vero. Asperiores aut hic sint ut voluptates. Facere consequatur ut rem nam excepturi iusto officiis. Possimus eum fugiat sed vero necessitatibus soluta. Qui nihil quis ut enim occaecati. Animi eos voluptatem aperiam vel in impedit adipisci. Aperiam qui nisi rerum eligendi occaecati voluptate quia. Ut dolores assumenda ipsa a placeat.', 2, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(15, 'Voluptates nihil molestiae aut expedita.', 8, 'Eum reprehenderit et quaerat hic at corporis. Ullam fugit sunt quos. Dicta illo doloremque est ut expedita eum reprehenderit. Vero et distinctio labore reprehenderit eius mollitia rerum et. Omnis cumque illum fugiat voluptates quisquam numquam iusto. Omnis explicabo consequatur et est autem in. Nobis autem quo assumenda possimus saepe. Magnam eligendi consequatur ut aut natus architecto aliquid. Fugiat natus est quod est ipsum temporibus sed ut. Minus quaerat enim eligendi. Consequuntur nobis aut officia nihil adipisci. Necessitatibus molestiae voluptas consequatur maiores neque repellat. Repellendus officiis facilis quos ut cumque aut ipsa. Aliquid rerum consequatur minima ea. Earum ut quo nam sunt deleniti et. Suscipit officia minus qui est. Cupiditate id ea consequatur accusantium delectus. Sunt odio nostrum molestiae voluptas. Quo ea officiis neque. Unde totam et modi ex minus. Id molestias quod amet ullam tempora. Adipisci libero aut veritatis aspernatur dicta commodi et. Aut ipsam velit expedita quod nihil quia. Ullam aut debitis quisquam natus qui molestias consectetur. Minima aperiam non saepe aut molestias. Est quas maxime sit et. Expedita praesentium ut nulla repellendus ducimus non. Incidunt modi provident enim iste. Dolor quaerat quia aut quis blanditiis. Rerum quia asperiores ea odio. Ut et sed voluptatem molestias aut id. Neque omnis vel reiciendis voluptatem consequatur nisi est. Qui nam inventore recusandae voluptatem voluptatem. Aperiam numquam repellat ad. Atque perspiciatis doloribus numquam saepe. Dolores tempore sit voluptas et aperiam sunt. Nemo quaerat sapiente expedita omnis. Rerum provident illum alias reprehenderit tempore dolores sequi rerum.', 5, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(16, 'Facilis velit quia est ut corrupti atque sunt sit.', 10, 'Et vel illo fugiat culpa enim reiciendis. Doloribus minus voluptatum corporis magni blanditiis. Ad dignissimos laboriosam autem odio ex ipsa repellendus nobis. Et consectetur harum minima quidem. Voluptatem ducimus sint aut voluptas nisi illum. Sunt nihil aut nemo id modi id. Placeat et quasi quia ab architecto facere est sed. Illum excepturi consequatur maxime consequatur et dolore repellendus dolores. Id autem veniam ea eligendi qui. Amet molestias et et. Eos dignissimos dolorem eos aut et asperiores ut et. Et in in aut porro. Maxime autem quia ut quia dolorum illum placeat consectetur. Amet sunt perferendis distinctio. Consequatur itaque blanditiis eos velit et. Sapiente magni vitae quibusdam rerum non necessitatibus eveniet. Quis soluta blanditiis facilis accusamus nemo consequatur. Aut omnis pariatur dolorem dicta sint. Officia deserunt qui sed quia. Tenetur voluptatem est suscipit totam a quas facilis quam. Dolorem iste vero ipsam voluptatem dolores rerum molestiae in. Laborum ipsa totam eos odio est dolor repellat. Dolorum est sed rerum pariatur. Ducimus et earum blanditiis sit. Omnis nihil animi velit autem earum pariatur dolorem.', 9, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(17, 'Laboriosam non enim tempora est consequuntur qui.', 7, 'Quo et perferendis natus neque doloremque unde id. Id sit molestias nostrum nemo voluptas rerum. Sit quas quia explicabo adipisci at sit laborum nemo. Ut ratione alias non fugit quia dolorem. Qui nisi quos nam rerum modi. Perspiciatis earum et adipisci sint eveniet quaerat. Nemo quis in consequatur et ut. Aut nostrum rerum dicta. Ullam doloremque harum non est voluptate. Atque doloribus et commodi mollitia eaque non sit. Aliquid incidunt vero ad qui. Fuga sed quibusdam tempora sapiente rerum. Perspiciatis voluptatem sint cum dolores. Ad blanditiis consequatur consequuntur et dolores corporis voluptates aperiam. Ea voluptates voluptatem debitis dolore. Illum omnis voluptatibus ex libero. Illo itaque corrupti iusto optio. Ad harum eius temporibus eaque enim. Occaecati et qui dolores facere ipsam. Quis aperiam enim quam illo.', 7, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(18, 'Consequatur quia alias inventore maxime.', 10, 'Iure atque delectus eaque itaque molestias nisi est. Beatae magni ipsam nulla dolores occaecati. Provident ea eveniet libero est autem iure fugiat. Id culpa deleniti praesentium dolorem non praesentium et. Eligendi consequatur sit aut quis quia saepe. Vel necessitatibus accusantium ut libero a. Deleniti quibusdam ipsum eum repellendus. Dolor recusandae quisquam molestiae tempore delectus maiores. Laudantium possimus at et. Est commodi consequatur dolor itaque occaecati odio officia. Sed suscipit exercitationem eveniet sit. Rerum delectus placeat quam. Culpa expedita dolorem asperiores iste. Eos nisi pariatur odio vero magnam vel libero. Et iusto eaque aut soluta sunt quia. Nostrum autem doloribus qui. In velit excepturi reprehenderit ut iusto. Omnis id deserunt accusamus molestias ut ab cum velit. Aut eligendi aperiam tempora veniam voluptas expedita quo. Molestiae praesentium debitis consequatur sit commodi dolor. Eaque nihil reiciendis hic. Quam laudantium ipsum enim earum. Vitae sit fuga quidem dignissimos laudantium. Dolor porro dignissimos sit dolorum. Et consectetur laborum possimus sint reiciendis consequatur. Aut qui voluptatem perspiciatis ad nesciunt modi. Fugiat est voluptates sint voluptatum. Et sed ex voluptas est itaque et aut. Et illum eaque eius corrupti dolores sequi. Voluptates quod libero aut ut. Et ut doloremque odit ducimus illo assumenda delectus. Itaque ipsam illum est. Pariatur illo molestiae non dolorum. Est temporibus quasi sint eligendi vero. Cumque a sint sit est omnis non. Repellat natus minus fugiat. Corporis eos illum voluptates perferendis. Explicabo totam perspiciatis est repudiandae aut. Reprehenderit voluptatibus labore consequatur quae impedit vero. Cumque et vero non quis sit reprehenderit eaque.', 6, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(19, 'Hic aut temporibus ducimus velit.', 10, 'Cupiditate consequuntur totam perspiciatis officiis veritatis. Dicta sit quod aspernatur impedit in. Perferendis corporis vero quia perferendis. Animi non doloremque corporis. Est et ipsa deleniti enim natus. Mollitia quo asperiores iusto et ut. Fugit et sit et. Qui assumenda placeat iure. Dolorem rerum dolore qui voluptatem. Corrupti eos magni tenetur sint. Voluptas ratione rem natus temporibus saepe quasi. Corrupti sit facere possimus vitae ut ab praesentium enim. Sapiente veniam dolor incidunt. Quisquam eos quibusdam voluptatem quaerat. Optio et aut consequatur alias. Quos quia ullam non enim sed. Qui minus officiis aliquid ullam. Modi et est quaerat provident. Aut accusantium omnis sit reiciendis. Ut eos quas aut et impedit. Illo recusandae fugit quae consequatur corporis doloribus. Quaerat aut dolor sed reprehenderit reiciendis excepturi distinctio est. Minima et ut aperiam fuga. Explicabo qui et sequi in omnis et praesentium ut. Asperiores molestias quod ut.', 8, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(20, 'Quo eius et molestiae delectus.', 2, 'Aut incidunt molestiae consequuntur. Et et asperiores quae rerum ex. Qui sed consequatur deserunt reiciendis sint impedit. Amet fuga consequatur qui blanditiis voluptas. Voluptatem facere qui aperiam saepe reiciendis aut alias. Et ut quam explicabo explicabo non. Fuga asperiores labore odit delectus ad similique laborum quae. Incidunt veritatis autem est velit debitis illum voluptate. Dolorem blanditiis vel perspiciatis ab aut eos quia eum. Quo commodi magni nulla voluptas qui repellendus nihil. Modi ex optio tempore ut unde aliquam et. Doloremque voluptatem nobis ipsum cum. Et molestiae sed sit aut est ad sed. Quas nobis totam omnis atque. Cupiditate assumenda animi atque quae voluptates repudiandae. Iusto ut aperiam excepturi qui error explicabo unde repellat. Sunt ipsum autem assumenda quia. Delectus quam suscipit omnis. Quo ea porro non est saepe. Dolores temporibus aut nisi architecto. Explicabo voluptatem molestias quos veniam facilis sit. Ut est harum ea. Consequatur minus voluptatem laborum ratione. Iste deserunt error eveniet nesciunt voluptas eius. In dolor aliquid debitis odio. Magni sit mollitia sed necessitatibus. Assumenda ipsam ratione et voluptatem qui officia. Ipsum omnis ipsam recusandae est fuga corrupti. Quo vel explicabo veniam molestias consectetur. Officia et quo reiciendis. Aut ipsam dicta non harum voluptatem. Omnis et architecto et nemo et. Numquam inventore dolores quidem nihil sint tempore explicabo qui. Quam sapiente tenetur impedit voluptates et magni reprehenderit minima. Alias et voluptatibus voluptatem accusantium repellat cumque vitae. Cum corporis debitis nisi suscipit voluptates. Totam voluptatem tempore quia molestiae corrupti laudantium qui. Distinctio nemo aliquid vel distinctio ipsum.', 3, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(21, 'Voluptates est ut qui dolores non ex.', 4, 'Aperiam enim voluptates eos molestiae. Quae accusantium ut et maiores quod optio. At quo et distinctio. At et soluta vero et aut reprehenderit velit enim. Culpa voluptas unde similique tempore a. Maiores et nihil quidem veniam minus et. Possimus sit ab aliquam id suscipit consectetur dolores. Laboriosam et et voluptatem minus omnis. Et ut qui officiis dolorum ipsum qui harum enim. Aspernatur reprehenderit impedit qui aperiam recusandae. Est est omnis ratione voluptates ut asperiores. Nulla ipsa ut qui natus omnis fugiat. Sequi praesentium dolor magnam voluptatem soluta qui. Enim nam recusandae nisi aspernatur velit dolorum. Ex autem sed rerum sint expedita deleniti. Fugiat voluptatibus ut omnis odit quos. Ipsam quis esse minima et quasi mollitia iste ut. Tenetur perspiciatis reiciendis numquam. Vero quasi et consequuntur qui provident. Accusamus facilis repellat iure et incidunt ut. Voluptatem qui et voluptatem soluta saepe. Enim et autem quia repellat doloremque. Enim rem vitae debitis provident quis minima. Voluptatibus in ab blanditiis nihil est. Consequatur quas ipsam necessitatibus illum. Autem repellendus qui fugit pariatur. Provident accusamus magni odio quo et. Iusto nobis voluptatem repellat sit perspiciatis totam. Eius nemo aut dicta doloremque impedit magnam dolor. Minima ullam dolorem modi est qui commodi dolor. Sit est aspernatur dolores iure. Aut aut possimus consequuntur natus nihil dolorem. Voluptate voluptatum delectus vitae fugiat nisi eos eveniet. Quisquam laudantium esse modi accusamus vel est. Dolore nobis ducimus voluptatum aperiam. Enim ipsum impedit voluptatem ipsa. Quia enim architecto iste est voluptas tempora. Repellat sit nam sed autem a molestiae. Minus quis sit quas deleniti placeat expedita quo. Aut harum dolorum eaque placeat sunt nihil necessitatibus. Magnam ut officia voluptate rem.', 4, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(22, 'Eaque recusandae dignissimos cumque quis.', 1, 'Maxime vero nihil earum quia iusto amet sed consectetur. Ipsa et velit nulla vitae ab recusandae eius. Saepe ut necessitatibus impedit nulla. Ut provident et quia voluptas. Asperiores voluptates maxime qui occaecati perspiciatis sint. Qui assumenda quasi quia. In distinctio et maxime laboriosam provident. Eos voluptatibus atque aut aut enim numquam. Ut aut et aut beatae consequuntur. Ut nihil est harum voluptatem explicabo ipsum perspiciatis ipsam. Necessitatibus eligendi totam molestiae commodi dolor vitae dolorem consequatur. Ducimus et non sed nostrum nobis explicabo aliquid. Sunt qui eum praesentium nobis sed. Iure rerum architecto vitae odio rerum ipsa. Non dolores impedit fugit aut et aspernatur repellendus. Ut et voluptatem reiciendis aperiam. Voluptate in sit molestias facilis quo fugiat animi. Quia et blanditiis quaerat porro sint. Accusantium voluptatem in debitis dicta ut est hic natus. Eum suscipit suscipit fuga quia cum sint. Ea ipsa consequatur impedit recusandae. Voluptas aut odit voluptatum impedit sit voluptatem aspernatur error. Quis non quidem molestiae dicta optio et aut consequatur. Voluptas magnam fugit ut nostrum eos totam eos eligendi. Alias aliquam quisquam ullam aliquid. Voluptates consequatur repudiandae sed odio distinctio qui omnis ab. Cupiditate delectus necessitatibus quaerat perspiciatis amet cupiditate in. Iusto velit enim dolores eum. Asperiores aut eius consequuntur repellendus ullam. Molestias ratione nemo officia non delectus et.', 7, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(23, 'Sed porro et velit exercitationem.', 2, 'Laboriosam non ea quasi accusantium architecto. Ab consectetur et modi sed. Molestias odio sapiente quis. Perspiciatis odio fuga ratione modi. Ea non assumenda voluptatem voluptatibus quis vel. Esse facilis officiis quidem adipisci. Doloremque soluta iusto harum ut qui dolorem quod. Magni voluptatem minus rerum. Laborum molestiae voluptate nihil suscipit sint dolor. Id voluptatem unde non qui commodi. Culpa sapiente amet aut sequi. Ut officia voluptas consectetur. Omnis sit placeat perspiciatis quos. Quos dignissimos porro et veniam sed. Ex autem doloremque ut molestiae aperiam aperiam. Ea sed quae ipsa doloribus quis soluta. Quia in vitae corporis impedit et. Saepe provident fugit ea ea autem expedita. Nobis illo illo tempora libero est. Nulla eaque soluta enim tenetur fuga non et. Tempore occaecati quam amet natus. Sed nihil blanditiis occaecati tempora repellat ex. Sit minima quibusdam ullam facere. Accusantium molestias inventore voluptatem quasi eos voluptatibus. Dolorem voluptates rem culpa sed magnam qui consectetur. Quo eaque recusandae rerum earum. Facilis est veritatis eligendi tenetur. Reprehenderit quia recusandae voluptatem reprehenderit mollitia. Voluptas quia facere aut. Id atque rem provident voluptate non itaque deleniti. Quibusdam quos fuga excepturi iusto beatae excepturi.', 3, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(24, 'Ut et sit occaecati qui eos atque ad.', 4, 'Veritatis ex culpa numquam quia beatae quas. Non qui est qui aliquam voluptas officia repellat. Natus unde totam laborum in repellendus illum provident magni. Veritatis saepe qui adipisci eum quod saepe eaque voluptatem. Quod enim quam recusandae eaque deserunt. Rem enim necessitatibus eaque nisi quia aperiam. Quidem aut ratione quis tempore. Sunt incidunt temporibus sint recusandae occaecati quas distinctio. Voluptas reiciendis laborum voluptas similique quod ex doloremque. Quae minus est magni voluptatem labore quae. Dolor enim est maiores aut quidem consequatur consequuntur corporis. In quae officia nobis adipisci natus et molestiae. Delectus non laborum officia sed sed expedita. Delectus nihil sit autem adipisci dolore ullam est. Consequatur aspernatur rerum quis vitae perferendis recusandae qui. Error autem temporibus et voluptate. Quia eveniet et et exercitationem eos iure a. Qui ut iusto harum voluptatem aut et ratione. Ut eum pariatur ipsa aut qui amet. Officia in velit autem laboriosam consectetur accusantium omnis repellat. Vel saepe commodi quis voluptatibus necessitatibus harum. Impedit unde corporis itaque est aut. Qui culpa dolorem est ad adipisci ut ut. Sunt consequatur voluptatum nulla quis repudiandae neque sequi. Eos nulla fugiat ratione sequi ut nobis consequatur.', 8, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(25, 'Harum vel omnis ad tempora placeat ducimus illo.', 10, 'Quisquam quasi quas voluptates quaerat assumenda totam quo facere. At quod quis quia necessitatibus. Odio minus velit ab omnis ea beatae iure sunt. Dolorem sint dolor veritatis illum veniam inventore necessitatibus. Consequatur laboriosam sint tempora quos inventore dolores quae. Voluptas pariatur dolor dolorem inventore animi possimus. Quos exercitationem a eaque distinctio dolore eveniet doloribus neque. Quia esse nam ea et et distinctio repudiandae earum. Quis pariatur et aut consectetur tenetur. Praesentium deserunt fuga dolorum. Minus qui at qui. Omnis vel laborum est quaerat temporibus. Praesentium maxime expedita non repellat quod id. Architecto ut voluptatem aspernatur veritatis officia animi velit. Molestias distinctio neque rerum. Accusantium est quia animi ratione quos a earum. Unde voluptas dolorum hic. Aut accusamus corporis in aut quia molestias quia. Non nesciunt facere doloribus rem numquam magni vel. Qui quia non et autem soluta omnis excepturi. Doloribus ratione dignissimos deserunt fuga dolores ex. Natus temporibus deleniti qui consectetur.', 9, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(26, 'Blanditiis harum molestiae rem ex nesciunt.', 9, 'Laborum amet rerum voluptate dicta. Minus voluptatum ut et ullam repellendus repellat. Reiciendis quia eum sed architecto id temporibus est. Dolorem nesciunt similique deserunt est. Error ducimus ducimus accusantium sit. Consequuntur nemo iusto consequatur numquam a voluptas ut molestias. Autem autem tempora veritatis enim eos ad. Vel dolor vel dignissimos et ut qui. Expedita est fugit dolores aut repudiandae consectetur nulla. Vel delectus doloribus omnis excepturi autem. Illum labore ea qui id amet sint qui. In quas earum tenetur voluptatibus veritatis ullam. Consequuntur modi quis sapiente velit. Aut quia ut ea enim. Deserunt provident voluptatibus atque reiciendis dignissimos nostrum asperiores ad. In assumenda ratione iusto. Voluptate nihil accusantium dolore ab enim. Quia error dolor aut aut impedit deserunt et. Nesciunt optio non dicta velit. Expedita quaerat sed dolorem perferendis cupiditate odio dolorum. Adipisci eos quis totam. Dolorum vitae recusandae beatae est. Nemo voluptatem asperiores vero error esse dicta. Deleniti natus ab repellat esse et sit. Tempore minus perspiciatis nihil officia. Illum optio in explicabo dolores doloremque. Error quis quo voluptatem quo. Deleniti iusto quo voluptas ex illum sit in. Vitae neque dicta quis sunt. Aperiam adipisci et harum esse voluptatem voluptates aspernatur sed. Exercitationem deserunt quia sed quo neque inventore. Modi doloribus quisquam et doloremque eius voluptas ut. Quidem aliquid voluptatem accusantium et porro harum. Sint veniam voluptatum et. Commodi enim nam vel minima. Veritatis vel mollitia voluptatibus a voluptatem saepe vel. Labore maxime molestiae eos est id tempore esse. Perferendis est veritatis corrupti soluta. Quis corporis quam reiciendis voluptas. Nostrum incidunt corporis cupiditate nulla blanditiis quis repellat. Praesentium non omnis aut.', 3, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(27, 'Iste nesciunt enim maiores est aut.', 6, 'Distinctio autem veritatis ullam qui dolorem voluptas quaerat. Commodi cumque enim est est distinctio ea enim. Eveniet enim velit possimus est labore. Enim quidem quos sint sit perspiciatis ab quo. Ipsam culpa et dolores sequi. Officia eligendi quia soluta blanditiis vero exercitationem ut. Quas voluptate ex error nesciunt impedit. Repudiandae vel maiores itaque vel facere autem. Deserunt modi sint nihil et. Labore aut ut rem dolorum ut. A et et facere labore rem. Excepturi fugiat rerum excepturi expedita. Modi autem et dignissimos rem. Ut qui est quidem ullam omnis optio esse. Sit qui quam et sed voluptatibus necessitatibus dolore. Porro ut quos labore iure. Sed qui iste molestias harum ipsam. Dignissimos amet corporis quaerat odit eligendi expedita blanditiis. Sed voluptatem et voluptas et necessitatibus accusamus. Temporibus quo ab quia et eveniet fugit beatae. Qui esse voluptas laborum expedita quis. Placeat aut quia qui dolores. Voluptatem est eveniet provident. Iusto nihil veritatis totam modi inventore. Qui ut autem magnam saepe porro. Iusto corrupti fugiat iusto nobis inventore eum eius. Debitis voluptas eaque tenetur nobis pariatur dolores est et. Provident laudantium autem facere neque ipsam doloribus et. Aut quidem autem in aut consequatur. Eligendi cupiditate quo sunt aut voluptatem cupiditate. Libero ut dolorem aut non in eius nostrum. Eos et dolorem itaque vitae suscipit eaque nesciunt et. Maxime laboriosam molestias accusantium dolorem. Libero eius voluptatem placeat iste officiis. Aut non expedita necessitatibus quia quis. Soluta aspernatur quam qui voluptatem molestias quis voluptatem.', 2, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(28, 'Sed ut explicabo ea eos omnis commodi.', 9, 'Neque libero quia sit. Nulla vero aspernatur quod deserunt ex et. Voluptatem exercitationem quasi quia voluptatem in. Ut ad nobis necessitatibus facere aperiam consequatur quibusdam est. Vel non nihil est. Numquam quibusdam id dolore non aspernatur occaecati. Ullam illum voluptas nesciunt aut maiores qui eius. Cumque aut placeat sunt dolorum placeat aut nihil. Saepe ut aut explicabo vero sed. Distinctio porro quo consequatur nihil. Eius culpa dolorem repudiandae est molestiae libero et. Similique sunt vero sit accusamus qui deserunt ab. Omnis eaque eius necessitatibus perspiciatis qui optio. Voluptate quia neque odio rem qui. Expedita illo velit sed vel. Odit molestias vero et unde. Tenetur quisquam aliquam rem dolor hic molestiae cupiditate voluptas. Quis eligendi sunt accusantium vel. Est aspernatur deleniti nihil. Quia nihil in blanditiis vel qui et. Voluptatem reprehenderit eligendi repudiandae sit laborum. Neque enim voluptate ea omnis. Incidunt saepe reprehenderit omnis qui delectus sint quasi ut. Quis magnam voluptas nemo et. Reiciendis vel quidem non delectus nihil ea facere. Voluptates est doloremque et mollitia et. Qui aspernatur in minus distinctio cum unde sint. Repellat quam consectetur perferendis nobis perferendis et minus. Ut odio cum quia doloremque ipsam vero dolorem. Quasi quasi architecto sit delectus esse. Impedit quam id vitae ea nostrum facilis tenetur. Eum aut vitae ratione voluptatibus veniam.', 6, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(29, 'Voluptatem voluptates doloremque et minus neque.', 1, 'Voluptatibus praesentium et cum id soluta vitae. Fugit quod magni praesentium saepe rerum hic repudiandae. Modi quasi corrupti a voluptate quidem cumque. Eligendi alias magni autem quia repudiandae magni. Nam consectetur hic animi voluptatem occaecati ducimus. Veritatis possimus necessitatibus excepturi et sed. Vero quas impedit temporibus eos iste ut. Aliquid ut veritatis quibusdam inventore similique voluptatibus. Quo quaerat sit ducimus neque delectus error. Sint consequatur repellat soluta maiores. Vero quia cupiditate ut. Omnis ex debitis consequatur. Omnis expedita a molestiae ut. Laboriosam eos natus sit aperiam. Aut corporis ipsa laudantium quam dolores non aut. Quasi dolor itaque aspernatur doloribus aliquid. Officiis eligendi saepe error laborum. Saepe non ut quis assumenda eos. Qui saepe autem dolores ab quod. Ut asperiores reprehenderit recusandae ut. Qui saepe modi et saepe quis distinctio debitis fugit. Dolor ducimus vitae molestiae praesentium deserunt. Qui libero qui veniam vel fugit similique. Ipsam molestiae itaque totam ea nulla. Et error suscipit laudantium provident tempore eveniet dolorum. Maiores repudiandae est soluta ratione illo. Excepturi dicta hic nisi.', 3, 'poster.png', '2021-10-28 19:05:48', '2021-10-28 19:05:48'),
(30, 'Culpa omnis excepturi recusandae tempore.', 7, 'Nostrum explicabo quos saepe quia minus est. Soluta adipisci enim non quas adipisci. Facere laudantium et laboriosam sunt et fugit. Impedit itaque fugiat deleniti sunt rem. Vel suscipit vitae vel dolor consequuntur cumque vero. Quam minus quia ea explicabo voluptates. Tempore temporibus at aliquam ut. Sunt deserunt aut autem natus omnis veniam aliquam accusantium. In ut facere beatae impedit rem fugiat. Voluptatibus deserunt aperiam omnis et optio est. Ipsam architecto fugit ut ut et. Ducimus hic et quasi quibusdam ex fugiat. Asperiores quia omnis eos nemo modi et. Et et omnis optio iusto quae. Quia distinctio vel sit tempora rem. Illo voluptatem odit veniam autem dolor. Ad eius eos ipsum facere ea. Recusandae sint perspiciatis et ut quidem. Sit repudiandae neque ut. Non qui quia facilis perspiciatis. Ut est impedit dicta velit minima sint. Iure qui voluptatem qui et dolorem quae.', 2, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(31, 'Dolor illo veniam quia sint et possimus non.', 1, 'Eos odio quo officia voluptatem est est suscipit. Excepturi voluptatem labore veritatis fugit quia. Qui ratione necessitatibus officia. Molestiae ut est suscipit deleniti iusto. Eligendi sit aspernatur sunt sed. Suscipit corrupti aut molestias tempore fugit qui. Modi facilis impedit qui blanditiis quo nihil. Sit inventore qui officiis fuga. Ut quod ex quia dolores ullam laborum minima. Aut ex enim asperiores voluptatem. Laborum non recusandae quas consequatur quis dolores. Quis consequatur temporibus deleniti et. Dolore vel quia repellendus ut explicabo et totam. Saepe natus nulla consectetur vel ut iste quo. Ad illum qui temporibus ab nulla ut amet. Qui dolores sint sequi ad neque aut necessitatibus. Est recusandae harum qui quaerat. Libero incidunt aspernatur at atque et odio quia. Minus voluptatum enim deserunt cupiditate et. Voluptate earum perspiciatis praesentium aut id dolor numquam. Qui et eos nesciunt minima non qui est.', 4, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(32, 'Dicta nihil ut dolorum ratione sed similique.', 5, 'Qui velit vero quia. Asperiores vel cumque ut ipsum quia et tempore. Nihil quibusdam animi assumenda repellendus quia sint debitis. Fugiat excepturi aut voluptatum laudantium. Quos optio assumenda eaque facere. Sed necessitatibus omnis tenetur qui. Dolorum culpa consequatur nihil fugit modi consectetur qui quia. Incidunt cupiditate qui architecto deserunt temporibus. Ducimus earum perferendis porro consectetur eos optio. Eligendi vero et ut aliquam maiores dignissimos. Quis dolorem consequuntur qui veniam. Nemo quaerat repellat eius et assumenda tempora dolorem. Vel nulla recusandae ut esse deleniti nihil. Velit esse atque ratione odio minus vero voluptatum. Soluta corrupti quisquam suscipit est ipsum est iusto. Necessitatibus est accusamus aperiam sunt debitis ipsa asperiores. Mollitia nam enim nulla et ut distinctio. Dignissimos consequatur impedit aliquam iste doloribus culpa. Delectus voluptatem fugit libero non non est explicabo. Eos vel sapiente ut itaque distinctio impedit. Inventore deserunt voluptatem aspernatur dicta. Est quo saepe sed. Veritatis dolorum porro molestiae sed. Qui dolorum eum rerum sit. Nisi beatae voluptatem ea autem. Vitae esse aut occaecati et odio. Voluptas cumque sunt quis aut voluptatem voluptates illum. Ullam non esse libero. Quia veniam et magni voluptatem dolorem officia. Voluptas consequatur unde et ipsa doloribus ipsum repellendus. Ea magnam dolores sit molestiae commodi. Amet nostrum enim quo aperiam accusamus quidem excepturi. Natus suscipit dolores voluptate quo exercitationem. Maiores sit et ut molestiae eius nisi aliquam aperiam. Qui voluptates in molestiae tempore ex quod. Et voluptatem vel aut voluptatem velit at. Consequatur nam illo aut et porro dolores unde. Vel veritatis hic quos impedit expedita numquam eaque.', 10, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(33, 'Et fugit cumque pariatur consequuntur at.', 4, 'Blanditiis at laborum culpa rerum ab error. Est modi illo recusandae maxime debitis. Itaque quia adipisci sit dolor assumenda. Et veritatis dolorem ratione omnis. Ut reiciendis sit expedita illo. Incidunt eos facere incidunt sit. Sit vitae repellat quae reiciendis. Doloremque quos quibusdam sint omnis qui eaque. Facere officia modi nulla nam magni eos id molestiae. Ea voluptate dolores est et rem est. Quibusdam et itaque molestiae sed aut sit praesentium amet. Dolor quia aliquam quia accusamus. Soluta est provident inventore repudiandae. Quaerat repudiandae corporis dicta optio aut dolorum qui. Sit sapiente impedit corrupti reprehenderit voluptatem possimus voluptatem totam. Dolores dolorem voluptatem ab omnis aut repellendus quam qui. Laboriosam a vel veritatis perferendis quasi ea. Delectus dolor quos deserunt. Consequatur dolor velit facilis atque sit quae. Nostrum veniam nobis molestiae quo nobis earum. Nihil non quis natus incidunt a qui. Reprehenderit laboriosam velit cumque tempora. Sit dicta magnam et ab delectus sapiente nulla. Iste dolorem voluptas vero reiciendis fugit nobis occaecati. Temporibus odit modi omnis. Fuga tempora et sit. Molestiae in ut architecto ut. Consequuntur beatae quo illo provident soluta. Repellendus consequatur sunt illo nostrum doloribus. Nemo placeat quia nostrum vitae totam porro praesentium. Blanditiis et nihil occaecati tenetur laboriosam consequatur. Corrupti ut eius exercitationem non vel autem. Dolorem veritatis veniam sed aut. Explicabo inventore commodi est qui. Dolor reiciendis reiciendis ipsum non ea neque velit sint.', 6, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(34, 'Culpa praesentium rerum culpa suscipit aut nihil.', 6, 'Omnis ut commodi minima laudantium consequatur ex. Quo voluptatem quis et delectus minus dolor. Necessitatibus consequatur consequuntur dolore possimus qui vel magni. Voluptatem molestias maxime beatae porro et amet. Eligendi excepturi rerum et harum similique voluptates consectetur. Ad animi voluptate pariatur et dolorem animi. Laudantium velit nostrum labore neque fugit repellat exercitationem. Quidem et assumenda et similique deleniti. Itaque voluptas tempore quo sed. Repellendus consectetur cumque quibusdam soluta placeat voluptates et. Beatae quia architecto voluptate. Est mollitia voluptas sapiente laborum. Qui facere dolores mollitia adipisci dignissimos nam. Beatae ad aut sunt reiciendis. Quam qui ut inventore autem aperiam quia tenetur. Eligendi facere sunt ut cumque dolores occaecati sit nostrum. Quisquam impedit sunt fugiat magnam hic molestiae. A consequuntur sunt nesciunt ex quidem et eum. Quia sunt neque esse dolorem delectus nemo. Omnis sunt quos aut dolor similique ut. A reprehenderit mollitia quidem non aut. Aut repellat quo ut ratione totam. Veniam molestias necessitatibus vel aperiam libero sint. Natus unde aspernatur quis consectetur cupiditate eius. Mollitia distinctio cupiditate nesciunt cupiditate. Excepturi ut quis enim cumque. Repudiandae voluptatum ut harum excepturi doloribus quo. Qui perspiciatis sed tempore ratione quia perspiciatis. Ut dolor deserunt quae sed vel tempora sed. Dolorem tempore aut quis harum ut. Non aut odio fugiat dolore ea consectetur corrupti. Ea sint eum qui repellendus voluptates. Voluptates ut atque aut. At illum quos voluptas consectetur commodi recusandae. Alias fuga dolores iste commodi eaque accusamus. Magnam veritatis non cupiditate quas natus voluptatem aut. Sit reprehenderit fugit labore velit beatae reprehenderit.', 1, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(35, 'Aut aspernatur alias sed aperiam voluptatem velit.', 2, 'Ratione sapiente nihil porro eum quasi. Nemo fugit assumenda minima adipisci exercitationem. Commodi qui ratione rerum autem doloribus facere. Sed fugiat tempore non et blanditiis aut unde. Ipsam inventore voluptates facere iure. Sint incidunt doloribus amet repellat quis ducimus. Odio asperiores repudiandae molestiae ratione. Debitis et dolor et voluptatem omnis repudiandae dicta. Voluptatem aut incidunt neque ut molestiae et ut. Quo in sit consequatur quo ad eaque. Minus impedit provident est voluptas repellat modi cumque. Rem suscipit veniam deleniti dolores sit. Reiciendis ut esse non. Exercitationem cum temporibus dolorem et ut. Quasi vitae dicta ab dolorum. Fugiat doloremque mollitia sint et ipsa nihil. Qui recusandae rem quam beatae nihil voluptas adipisci. Qui non ratione cupiditate veniam commodi. Odit id voluptatem porro dolores. Reiciendis voluptatem aut et incidunt. Aliquam aut et nostrum ratione iusto autem adipisci.', 6, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49');
INSERT INTO `posts` (`id`, `title`, `admin_id`, `description`, `category_id`, `poster`, `created_at`, `updated_at`) VALUES
(36, 'Molestias sunt autem voluptas.', 9, 'Ducimus officia aut quod incidunt quis eos. Perspiciatis ipsum fuga eius sit voluptas. Qui accusamus placeat sit ex velit at laudantium. Illo dolores eligendi et dolores commodi quae vel. Amet beatae nisi ea tempore. Et laboriosam ut sunt dolorem quia eligendi. Qui dolor molestiae ut nesciunt quisquam enim. Est itaque incidunt dolorem voluptatum cupiditate asperiores. Eos placeat laudantium ut possimus quo excepturi. Sed vero aspernatur adipisci architecto. Nulla sed alias ad pariatur. Praesentium incidunt pariatur quia et repellendus nulla quia. Fugit omnis sunt nostrum aut molestias illum occaecati. Rem fugiat et architecto voluptate est officiis vel. Et exercitationem quod ea ad. Iusto cum earum omnis voluptate. Et nam quam ea impedit voluptas. Et veniam aut rerum et fuga dolore. Quisquam deserunt necessitatibus harum dicta qui aspernatur illum. Eveniet ea ipsa repellendus est aperiam nostrum quis. Voluptas temporibus magni officia deleniti est. Occaecati quasi qui inventore repellendus. Velit exercitationem est eaque error. Dolor sed nemo molestias sunt sit voluptate. Excepturi sit quis quia est omnis atque. Accusamus quaerat ea vel minus. Cum qui ipsum nemo excepturi laboriosam. Pariatur ab voluptatibus esse eum nesciunt molestiae in. Hic natus qui vel magni ut saepe nisi ut. Eaque exercitationem labore ut quis possimus id totam. Recusandae dolore mollitia asperiores ex vel hic fugit temporibus. Qui corporis harum magnam id beatae natus. Quidem et rerum quis ut qui. Beatae reprehenderit sunt voluptates.', 6, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(37, 'Est voluptatem iure tempora excepturi similique cupiditate.', 3, 'Ut excepturi vel saepe voluptate quo a. Quidem dignissimos aut deserunt eos suscipit asperiores. Voluptates est animi enim sit qui. Quia sit provident et qui voluptatum dolorem est. Voluptatem odio omnis voluptas nobis delectus aspernatur illum. Facere non sunt et sit magnam similique tempora. Autem et ut tempore fugiat. Eum consequatur minima ad eveniet velit dignissimos. Quibusdam perspiciatis et ipsa et culpa labore reprehenderit ut. Aliquid totam et quasi reiciendis doloremque. Soluta omnis culpa voluptas quam ut. Iste id libero nobis sit impedit ducimus nostrum. Dolore officia aut ut pariatur culpa. Qui sequi eum molestias assumenda et nulla quibusdam. Et voluptatem sed voluptate sed nostrum aut. Repellat numquam error voluptatem qui mollitia. Vel itaque facilis reprehenderit blanditiis consequuntur. Nulla facere ducimus totam unde. Non illum deleniti molestiae. Ipsum eum commodi quis placeat et dolore. Necessitatibus recusandae sint magnam architecto. Dolorem quae accusamus est maiores ducimus ratione quos. Eveniet quis mollitia quos ab voluptatem. Ducimus asperiores ut sunt.', 4, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(38, 'Est temporibus consequatur porro possimus sed sint veritatis.', 9, 'Consectetur sit in ea dicta. Deleniti modi autem suscipit ut illum. Eos laboriosam incidunt explicabo. Accusantium maxime est beatae nihil consequatur labore aut. Laboriosam eos rem culpa neque rerum possimus. Aperiam ratione omnis et molestiae dolores. Omnis facere fugit fugit a. Aut enim beatae quia ea consequatur. Dolores natus labore aperiam perspiciatis. Sit ut molestiae quia esse dolorum. Labore velit natus expedita assumenda. Dolorem voluptatem laboriosam et recusandae odio eum. Libero dolorem totam repellat modi. Temporibus nihil quo expedita ipsam aliquid. Illum voluptatem iure voluptatem vero quis in. Voluptatem voluptatem velit placeat. Expedita et ut enim doloremque aut. Tenetur nemo iste illo eveniet ut rem. Qui alias non maiores consequatur neque quam. Esse et nesciunt suscipit sapiente sit rerum. Ab ut aut nostrum sit. Molestias quaerat repellat tenetur est omnis est quia. Quaerat quaerat odio et omnis optio aut. Quia quia quaerat aut delectus. Id doloremque consequatur esse et sequi et sunt. Consequuntur tempora iure reiciendis tenetur quia. Perferendis aut at illo unde assumenda sit quia. Pariatur laborum ratione praesentium explicabo aliquam corporis. Maxime veniam omnis ad dolorem commodi est deleniti. Inventore facilis quas dolore nemo consequuntur omnis. Ut iste aut quod cupiditate. Nesciunt velit et est nostrum voluptatibus excepturi atque et. Ut sunt iusto consequuntur non voluptatem ut quis libero. Delectus veniam corrupti distinctio aut eos repellat. Quis tempora totam impedit maiores numquam consequuntur animi. Reprehenderit voluptate velit ab velit nobis aut minus. Aperiam excepturi eos est aperiam sit doloribus ut.', 4, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(39, 'Quibusdam reiciendis eius iure reprehenderit adipisci placeat.', 1, 'Repellat mollitia est cupiditate nam possimus repudiandae beatae. Est sed quas ut rerum soluta qui. Accusamus accusamus aliquam nemo et. Blanditiis rerum fugiat dolorem veniam repudiandae qui et molestiae. Totam nobis et laboriosam omnis fugit corporis ipsam. Excepturi debitis perferendis aut qui neque blanditiis. In blanditiis similique vel excepturi laboriosam commodi dolorem. Laudantium omnis qui consequatur dolor molestiae et. Autem et ut eaque minima voluptatem. Nisi itaque odit cupiditate quia. Porro inventore ut recusandae est aut. Provident voluptas at necessitatibus reiciendis et aut atque. Doloremque quo soluta sint libero nam et ut. Voluptatem earum perferendis velit quis recusandae et. Non est temporibus voluptatem quas. Illo cupiditate quidem harum cum aut. Provident eligendi praesentium cum omnis rerum sit. Dolore repudiandae praesentium error. Voluptatem aut consequuntur nobis iste. Non a sit dolorem voluptas. Quibusdam voluptatum esse qui itaque. Repellat sapiente nemo amet veritatis dignissimos deserunt cumque. Earum modi architecto ut. Ipsam velit recusandae doloremque eum est. Sunt alias modi aut quia. Aut laborum ipsam veniam maiores nulla sed omnis quos.', 9, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(40, 'Nam enim id fugit ad eius natus.', 4, 'Et quisquam possimus magnam qui eligendi. Id perferendis qui aspernatur qui ut quis exercitationem. Quae nostrum dolor non ex. Omnis nihil voluptatem enim qui eos. Fugit impedit eius distinctio consequatur repellat voluptatem rerum veritatis. Velit provident labore recusandae qui et sed. Vitae asperiores consequatur impedit et neque neque sit similique. Delectus temporibus accusantium quam voluptatibus. Eius explicabo dolore ducimus debitis non sunt explicabo. Voluptas id nihil dolorem delectus deleniti. Facilis quaerat modi officiis aut quas minima. Aut veritatis et enim fugit omnis possimus odio. Ullam illo iure quia molestiae qui dolorum. Animi quisquam possimus sequi suscipit. Id ut tenetur dolore a. Minima maiores quibusdam rerum earum. Necessitatibus possimus ipsam aspernatur qui itaque distinctio. Molestiae unde possimus consequuntur adipisci est aperiam repudiandae. Nostrum iure accusamus dolorem ut accusantium eum maiores. At quo consequatur quasi autem quam vitae. Aut laboriosam ipsa atque beatae dolorem blanditiis. Amet aut labore debitis suscipit. Et optio minima voluptatum laudantium omnis. Omnis asperiores officia quae aut aperiam. Quo tempore rem doloribus ullam maiores. Laborum consequatur ducimus numquam magni consequatur sunt. Aliquid est consequatur architecto ad et omnis laboriosam ipsum.', 8, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(41, 'Totam voluptatum est quae pariatur.', 4, 'Consequatur itaque est reiciendis est. Nisi placeat distinctio beatae temporibus nihil rerum et. Laborum suscipit omnis esse voluptatem. Et doloremque earum porro. Consequuntur eaque eveniet eligendi officia aliquam. Ut perspiciatis fuga in aperiam omnis porro. Dolore veniam quo aut quo ut. In est qui consequuntur. Quia est ex vel dicta. Autem ipsa nihil magni odit. Ducimus magnam aut quae. Beatae cumque iste temporibus quidem repudiandae porro. Modi temporibus eum non numquam magni. Repellendus in eligendi tenetur asperiores. Animi ratione voluptatem corporis dolores unde. Ut minus et commodi voluptatem est commodi. Aspernatur neque et rerum est. Illum qui culpa laborum et dolor sapiente et. Molestiae tempore id occaecati nobis rerum. Voluptatem voluptas eos voluptatum totam molestiae corrupti non. Est deserunt minus modi maxime dolores. Molestiae repellat odit delectus neque dolores est architecto eius. Quisquam magni omnis consequatur aut ut sapiente. Ipsa nemo totam dolorum vel voluptatum ea.', 5, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(42, 'Optio est explicabo molestias.', 7, 'Quibusdam facere distinctio quis magni saepe aliquid. Rerum soluta omnis id et qui earum sed sapiente. Eaque et porro quo omnis saepe. Quidem et dicta et non quis repellendus. Reprehenderit cupiditate molestias necessitatibus eaque. Et nisi totam voluptatem qui expedita doloribus reprehenderit. Non ut velit ab consequuntur voluptatem nostrum cumque. Sunt deleniti tempore cumque. Ea dolorem voluptatem eum. Et neque facere sequi tenetur. Molestias nemo quibusdam nam. Earum asperiores voluptas vel est a. Nisi distinctio aut aperiam inventore qui minus unde. Consequatur sed sit eos eum qui temporibus. Ab numquam voluptatem fugit velit. Iste assumenda quisquam autem minima architecto. Eaque quasi illo in debitis. Distinctio aperiam sed facilis et eos. Dolorum quia necessitatibus maxime eum non dolores ea. Labore ut et expedita deleniti. Molestiae corrupti corrupti eaque. Molestiae sint reprehenderit in. Alias accusamus ut sed consequatur assumenda. Laborum repellendus autem consequatur ut. Et expedita quam facilis vel qui soluta corporis. Aperiam quaerat amet sequi iure ex mollitia in. Voluptatem eum non temporibus cumque totam. Ut quod et earum omnis consequuntur autem doloremque. Voluptas dicta et voluptas quibusdam debitis et omnis accusantium.', 9, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(43, 'Quisquam modi itaque consectetur laudantium dolore enim quod omnis.', 2, 'Maxime maxime pariatur voluptate. Asperiores consequuntur quos totam autem. Perferendis et et quia optio. Dolor enim aut debitis quaerat ut est sapiente. Quod aspernatur dicta quia quidem ducimus odio. Sunt assumenda et dolores aut omnis. Vel dolorem ut exercitationem tenetur fuga recusandae. Ratione minima iste eligendi molestiae quidem. Repudiandae nam quae et repellat dolor voluptatibus dolore. Maxime a repellendus quibusdam harum aliquid. Placeat nisi non officia quos. Corporis eum expedita dicta exercitationem adipisci. Iusto quia et dicta nemo ex totam laudantium. Ipsum consectetur molestias veniam reprehenderit ullam recusandae. Deserunt ut mollitia ut adipisci. Mollitia voluptatem corrupti ut dolorem voluptatibus non voluptatem quam. Minus voluptatem ut laudantium eius sapiente. Aliquid pariatur dolor eum. Labore voluptatem aut deserunt voluptatem velit. Iste et qui et quod aut similique inventore. Autem sed recusandae velit velit officiis. Tempora labore officiis eligendi veritatis et possimus. Voluptatibus quae est rem ad molestiae atque. Minus assumenda exercitationem excepturi reprehenderit sequi nesciunt iste. Fuga ut voluptatibus non. Temporibus ea itaque hic velit blanditiis. Asperiores eveniet fugit officia omnis similique porro. Dolorem sunt sint necessitatibus. Et officia voluptas est.', 10, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(44, 'Quasi amet voluptatibus et eum fuga non eum molestias.', 7, 'Odit doloremque qui deleniti accusamus. Expedita fugiat eum qui quibusdam dignissimos qui et. Illum eaque sed asperiores ut. Ut a deleniti doloremque amet voluptate. Quam est voluptate quo asperiores aut quae. Voluptatem natus voluptatem animi modi sit. Et explicabo alias voluptatem ut qui. Eos necessitatibus similique non eligendi. Sed quod dolorem tempora et error ut. Est dolorum distinctio beatae nisi. Quia laboriosam at distinctio et sit in. Enim sit consequatur rerum delectus dignissimos. Aliquam dolorum quo fugit voluptatem incidunt. Veniam sed eum vitae doloremque qui officiis distinctio. Ut sapiente labore dolorem nisi tempora maiores veritatis. Est aut vel animi ea odit. Harum amet culpa qui nihil fugiat voluptatem. Temporibus porro modi et necessitatibus beatae. Ducimus architecto numquam a nemo maxime sunt. Sit quia consequatur harum enim et quaerat qui. Neque ut quod sed neque vel dolorem debitis quidem. Vel animi doloremque ut tempore. Perspiciatis temporibus voluptatem harum quo. Provident dolorem cupiditate non facere doloribus quod minima. Dolores non et rerum a quia asperiores fuga aut. Provident sed earum sint magni ut. Ut id laborum et neque debitis id impedit. Illum omnis sint accusantium porro aspernatur excepturi eveniet. Magnam doloribus aut molestiae facilis sapiente voluptate ut. Nemo impedit tenetur accusantium consectetur ut vero. Ipsam non commodi laudantium sit quos in. Consequatur laudantium et sit nemo qui ipsa porro laborum. Unde vitae dolore vel deserunt ea natus et rerum. Sequi laudantium rerum autem harum. Hic ex provident aut ut.', 7, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(45, 'Eos eos ipsam rerum atque nihil dolorem.', 8, 'Eveniet commodi quam a et accusantium. Veniam dolor accusantium quia voluptatem nesciunt. Blanditiis sit beatae voluptates molestiae impedit qui vel. Quisquam corporis necessitatibus quaerat error. Incidunt repellendus dolores quisquam ut qui iusto excepturi quis. Iusto vel aut id ex quia eos aperiam. Alias esse est et nisi voluptatem exercitationem. Quos iste cum molestias dolorem dolorem repellat dolor. Et ab voluptatem ullam quam repellat iusto at. Et repellendus molestias molestiae labore autem. Eos consectetur consequatur eius qui modi quos. Est cumque hic et. Occaecati voluptatem eos iusto asperiores. Incidunt velit blanditiis maiores consectetur illum. Sint tempora esse est cupiditate iure. Et sit rerum inventore assumenda ratione qui rerum. Atque nihil sequi architecto ut doloribus quo nostrum. Distinctio dolor enim tenetur eos. Et occaecati in aut. Doloremque est eveniet maiores est ipsam et non enim. Explicabo dicta rerum minus totam omnis optio. Animi ratione et rerum asperiores voluptates. Error et neque mollitia nobis. Rerum eaque maxime eos facilis eos et modi incidunt. Enim nulla molestiae dolorum. Non iusto ut voluptas ut doloremque. Eum eum suscipit ut odit non. Omnis nihil beatae aperiam quaerat illum. Blanditiis ut laudantium eveniet aperiam. Omnis libero soluta id officia qui reprehenderit ut. Corrupti rerum recusandae eos eos sed atque nobis.', 6, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(46, 'Odit repellat et quae natus facere soluta.', 10, 'Soluta qui et modi ab voluptatem aut quisquam. Magnam nihil unde minus molestias. Quam reiciendis dolores excepturi. Nemo suscipit est est est. Est aut et facere delectus. Cupiditate ipsa quos consequuntur temporibus. Quo totam at quam voluptas dolorum facere inventore deserunt. Fugit aut quibusdam voluptatem modi aperiam. Tempora quia dolore dolor dolor aut numquam at. Non adipisci eum nisi facilis molestiae sit quis. Esse cupiditate eaque cupiditate est maiores. Temporibus laborum eius eum in. Quibusdam voluptas qui sunt voluptatem. Voluptatem nam voluptatum occaecati nulla necessitatibus optio ab. Soluta vero labore officia rerum reiciendis. Porro sint modi sit distinctio. Necessitatibus voluptatem voluptatem non et mollitia doloribus. Nihil earum minus ducimus nemo. Qui minus voluptatem numquam harum. Iure quisquam adipisci libero ea totam rerum et. Veritatis at ipsa labore quis accusantium. Adipisci dolor rerum quia sit mollitia sequi qui minima. Aut ab quod placeat ipsa voluptates reiciendis. Molestiae et sit possimus aut nobis. Est at rerum provident non quos voluptatem commodi unde. Eaque maiores temporibus nihil aut perspiciatis voluptatibus. Neque officia et maxime. Corrupti et quod provident sed provident. Iste dolor odio pariatur tempora ut omnis. Inventore omnis neque quasi quia eaque. Natus occaecati praesentium aliquam quis illum. Non ipsam ipsum debitis nihil qui pariatur. Doloribus libero illum provident sit. Laborum voluptatibus quisquam eum aut veritatis perspiciatis quibusdam. Consequatur sed eos in.', 2, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(47, 'Sed ad adipisci sapiente beatae blanditiis.', 7, 'Enim sed molestias assumenda accusantium exercitationem. Omnis aut neque sed. Praesentium qui consectetur voluptatem nostrum impedit qui est. Quae nulla dolorum sed. Adipisci voluptatem accusamus labore voluptates. Et quis laudantium assumenda omnis culpa et occaecati quisquam. Consectetur asperiores itaque excepturi qui enim laborum. Tempore voluptatem eveniet alias illo voluptatem sapiente aliquid labore. Et quae sapiente non in. Provident sed quibusdam maxime eos qui. Quis voluptatibus commodi cupiditate quas nostrum voluptatem in impedit. Sapiente rerum id ex qui omnis repellat consequuntur minus. A consequuntur esse aut enim. Quia asperiores doloribus laborum dignissimos a veritatis. Ratione non molestiae beatae ut. Quia qui et id dolorem qui et nulla. Alias in et doloribus delectus qui dolorem inventore. Velit sint dolor enim est voluptatibus natus. Sunt recusandae laboriosam omnis. Quaerat suscipit vero optio fugit autem. Vel molestiae et quae. Nihil asperiores qui libero. Accusantium alias exercitationem harum molestias tempora. Ipsa et sit omnis voluptate. Consequatur quas minus facilis sit aut est placeat iste. Totam quod excepturi unde delectus laborum aut harum aut. Et earum qui suscipit quaerat. Velit ut consectetur natus. Quaerat ut reprehenderit incidunt iure neque. Natus molestiae tempore nulla repellendus iste. Vel ea libero sit similique. Consequatur reiciendis numquam voluptatum ducimus velit voluptatum. Sed ipsam eos necessitatibus quae. Molestiae cum quis sequi nostrum voluptatem. Repellat tempora rerum ab delectus eveniet eligendi esse. Iure assumenda assumenda est distinctio nam aut. Hic beatae est facere aut quia quia et. Dolorem non voluptatibus adipisci maxime est explicabo id. Et corrupti numquam eligendi nobis. Temporibus aut saepe nisi vitae tempora. Doloremque consequatur ut in. Nisi eum vero exercitationem deserunt exercitationem assumenda.', 10, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(48, 'Reprehenderit illum quibusdam voluptatibus dolore mollitia aut.', 9, 'Quas exercitationem nihil et aperiam in repudiandae atque ullam. Eum voluptatibus qui est. Quod illo fugiat beatae qui harum nobis. Sunt commodi eum mollitia harum. Adipisci rerum eum quia exercitationem et. Totam esse non molestiae et aut debitis. Ullam amet quasi dolorum magnam. Quibusdam numquam nihil maiores soluta modi. Et tempora in vero nisi libero. Omnis id aut cum accusantium. Ipsam maiores blanditiis non aut sit. Magnam qui et in iure ut praesentium eveniet. Et voluptatum quia qui quia. Beatae ut voluptates provident distinctio. Harum quae praesentium omnis est placeat ratione. Ut velit ipsum quia voluptatem et. Accusantium animi laudantium dolorem molestiae ex nobis tempora quam. Tenetur rerum dignissimos delectus culpa inventore veniam sit fuga. Nihil architecto excepturi quas. Quisquam sit natus totam quidem quidem voluptatum. Perferendis sunt consectetur voluptatem voluptate assumenda. Sint eos ea repellendus omnis quibusdam. Laborum odio laborum hic. Repellat consequatur nam sed vitae at et rem non.', 9, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(49, 'Est amet dolores vitae.', 7, 'Consequuntur nesciunt numquam provident eos accusantium perferendis deleniti. Optio tempore est voluptatem blanditiis consectetur dolorum rerum. Natus qui natus ut molestiae numquam. Sapiente ut nemo in illum voluptatem. Qui quas quod dicta dignissimos molestiae quis et. Dicta reiciendis cumque expedita id consequatur suscipit ipsam. Ut architecto id officia nulla odio at quia. In est voluptate velit saepe odit fugit exercitationem. Ipsum autem in quae autem dolores minima laboriosam. Inventore earum consequatur quo error expedita necessitatibus qui voluptatum. Repellat accusamus non rerum id recusandae deserunt magni. Blanditiis earum numquam consectetur a necessitatibus quod. Quis et quae officia est distinctio placeat quo. Qui ut et animi impedit quis. Sit ut quo praesentium sit saepe enim. Hic non ullam nam culpa. Id nemo consectetur totam quo. Odit similique aut ut voluptatum velit natus. Qui nulla atque rerum dolorem consequatur. Dolor est eum et est qui fugiat. Ratione at non omnis nesciunt.', 6, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(50, 'Corporis sed aut tenetur.', 5, 'Voluptatum qui mollitia vel enim libero officiis pariatur. Recusandae earum unde dolore. Ea ipsam non ducimus veniam eos ut sed cumque. Reiciendis earum reprehenderit sed. Voluptas nesciunt quam quia veritatis et voluptatum et. Omnis ea aliquam fuga adipisci. Qui aut voluptatem voluptates id. Et debitis vel quidem tempore voluptates non. Repudiandae doloremque est qui totam qui dolore exercitationem. Velit est rerum quis ullam corrupti reprehenderit iusto. Exercitationem illo incidunt id esse aut consequatur. Numquam adipisci est quae et. Inventore et id earum autem sit ex eveniet. Eum vitae molestiae eos esse voluptas recusandae ut. Aut dolor quas facilis assumenda ex error molestias dicta. Ut ratione est nisi temporibus nesciunt est est. Rerum enim aspernatur in in nisi sit facere. Veritatis voluptatem excepturi porro corrupti quia. Nulla reiciendis eveniet quas maxime et optio. Officia et consectetur officia minus explicabo. Consequatur et quia voluptatem. Enim sapiente itaque id odit eaque vero et assumenda. Sapiente dolor saepe accusamus et libero. Voluptatem quasi dolore consequuntur facere. Dolorum id eum nemo tempora est reiciendis numquam voluptas. Qui tempora voluptatem quod aut explicabo vitae sit. Voluptas ipsa et ducimus doloremque alias assumenda nihil quisquam. Quidem dolor voluptatem vitae molestias pariatur sed dicta aperiam. Distinctio sit laudantium consequuntur labore nulla qui. Perspiciatis nisi velit quia repellendus. Velit consequatur qui consequatur sapiente. Commodi quia maxime minus aut consectetur vel in. A eius et eos et sed quis laborum magnam. Dolor saepe ut magnam dicta. Animi vel eos rerum eaque voluptatem qui. Quia voluptatem minima sit itaque non. Et sed sapiente voluptas eveniet sit nesciunt. Aliquam et dolor tenetur et blanditiis eos illum. Aut similique earum possimus nam. Aperiam vel et ipsum ut nam autem aut. Magni ex necessitatibus ut porro sunt iste. Dolore ut sapiente ab enim qui.', 6, 'poster.png', '2021-10-28 19:05:49', '2021-10-28 19:05:49'),
(51, 'Action 1', 3, 'xxxxxxxxxxxx', 1, '617b07ec9f83a.jpg', '2021-10-28 19:28:28', '2021-10-28 19:28:28');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(10) UNSIGNED NOT NULL,
  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role_id` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `password`, `remember_token`, `name`, `role_id`, `created_at`, `updated_at`) VALUES
(1, 'whahn@example.net', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'F4F0ckD5ck', 'Colten Padberg IV', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(2, 'equitzon@example.net', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'GxDsH2c4AE', 'Trevion Koelpin DDS', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(3, 'hans36@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'U8sLSynq7B', 'Gwendolyn Stoltenberg', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(4, 'carson00@example.org', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'giGMEz7Mdv', 'Miss Vernie Jakubowski', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(5, 'alford82@example.org', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'AcHah6HwU0', 'Annalise Swift', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(6, 'emmerich.damien@example.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', '8FPdwzS3aJ', 'Vallie Feest', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(7, 'qkohler@example.net', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'sNYXlwf3Sw', 'Ettie Little', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(8, 'hauck.vallie@example.net', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'zF1G0tYMYl', 'Delores Raynor Jr.', 3, '2021-10-28 19:05:50', '2021-10-28 19:05:50'),
(9, 'omedhurst@example.org', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'vyAuQ9Cslo', 'Michael Raynor', 3, '2021-10-28 19:05:51', '2021-10-28 19:05:51'),
(10, 'agnes92@example.org', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'yi08Z8FXNj', 'Baron Frami', 3, '2021-10-28 19:05:51', '2021-10-28 19:05:51'),
(11, 'boniface.ebuka@gmail.com', '$2y$10$ogBZYh5k1GIOWVLFVJPO..k0NVOzUC4nRe1iyYXYczxRuvdiB46ZS', NULL, 'Agbp', 0, '2021-10-28 20:22:06', '2021-10-28 20:22:06'),
(12, 'bonifaxce.ebuka@gmail.com', '$2y$10$oMpIhLpqGIFi1Bkc91lRYeOwrDu4bCzJwNk0/UoEX4QZTq81eCVsu', NULL, 'Agbp', 0, '2021-10-28 20:23:58', '2021-10-28 20:23:58');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `categories_name_unique` (`name`);

--
-- Indexes for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `oauth_access_tokens`
--
ALTER TABLE `oauth_access_tokens`
  ADD PRIMARY KEY (`id`),
  ADD KEY `oauth_access_tokens_user_id_index` (`user_id`);

--
-- Indexes for table `oauth_auth_codes`
--
ALTER TABLE `oauth_auth_codes`
  ADD PRIMARY KEY (`id`),
  ADD KEY `oauth_auth_codes_user_id_index` (`user_id`);

--
-- Indexes for table `oauth_clients`
--
ALTER TABLE `oauth_clients`
  ADD PRIMARY KEY (`id`),
  ADD KEY `oauth_clients_user_id_index` (`user_id`);

--
-- Indexes for table `oauth_personal_access_clients`
--
ALTER TABLE `oauth_personal_access_clients`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `oauth_refresh_tokens`
--
ALTER TABLE `oauth_refresh_tokens`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `password_resets`
--
ALTER TABLE `password_resets`
  ADD KEY `password_resets_email_index` (`email`);

--
-- Indexes for table `posts`
--
ALTER TABLE `posts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `users_email_unique` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `failed_jobs`
--
ALTER TABLE `failed_jobs`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;

--
-- AUTO_INCREMENT for table `oauth_clients`
--
ALTER TABLE `oauth_clients`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `oauth_personal_access_clients`
--
ALTER TABLE `oauth_personal_access_clients`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `posts`
--
ALTER TABLE `posts`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
